---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u5681642/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -r img $DEPLOYPATH
    - /bin/cp -r js $DEPLOYPATH
    - /bin/cp -r lib $DEPLOYPATH
    - /bin/cp -r mail $DEPLOYPATH
    - /bin/cp -r scss $DEPLOYPATH
    - /bin/cp -r video $DEPLOYPATH
    - /bin/cp -r img $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp article.html $DEPLOYPATH
    - /bin/cp article1.html $DEPLOYPATH
    - /bin/cp article2.html $DEPLOYPATH
    - /bin/cp article3.html $DEPLOYPATH
    - /bin/cp article4.html $DEPLOYPATH
    - /bin/cp article5.html $DEPLOYPATH
    - /bin/cp article6.html $DEPLOYPATH
    - /bin/cp article7.html $DEPLOYPATH
    - /bin/cp article8.html $DEPLOYPATH
    - /bin/cp Artikel Bunga.docx $DEPLOYPATH
    - /bin/cp Artikel Cintania (1).docx $DEPLOYPATH
    - /bin/cp Artikel Wanti.docx $DEPLOYPATH
    - /bin/cp blog.html $DEPLOYPATH
    - /bin/cp Company Profile Gifera.pdf $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp project.html $DEPLOYPATH
    - /bin/cp logo 2.png $DEPLOYPATH
    - /bin/cp REPORT ARCHITECHNO 11 NOVEMBER 2022.pptx $DEPLOYPATH
    - /bin/cp service.html $DEPLOYPATH